### ISSUE TITLE
No instance for (NFData Class)

### ISSUE THREAD

**Issue by mohanzhang** [creswick/chatter#22]
I am trying to use the library in a stack project (tried with both `lts-3.8` and the most recent `lts-3.12`), and I'm getting the following error:

```
   src/NLP/ML/AvgPerceptron.hs:86:10:
        No instance for (NFData Class)
          arising from a use of ‘Control.DeepSeq.$gdmrnf’
        In the expression: Control.DeepSeq.$gdmrnf
        In an equation for ‘rnf’: rnf = Control.DeepSeq.$gdmrnf
        In the instance declaration for ‘NFData Perceptron’
```

My dependency versions are:

```
- cereal-text-0.1.0.1
- fullstop-0.1.4
- regex-tdfa-text-1.0.0.3
- tokenize-0.3.0
- chatter-0.8.0.0
```

Any idea why this might be happening? Is using GHC 7.10.2 an issue?

**Comment by travitch** [comment]
This is fixed by #17.  The issue arises because GHC 7.10 ships with a newer version of deepseq, which changes the default implementation of `rnf` for `NFData`.  The old default implementation is a no-op, so the `instance NFData Perceptron` in that file, which contains a `Class`, never needed the `NFData` instance for `Class`.  The new default implementation of `rnf` (which is included with GHC 7.10) uses generics to automatically recursively apply `rnf` to all contained values; this actually uses the `NFData` instance of `Class`, which was absent.

Note that the instances are now present, but they don't actually quite do the right thing on older versions of deepseq.

**Comment by mohanzhang** [comment]
Doh. Should have looked more closely at the latest commit on master -- says it right there! Thanks for the quick response. Any chance we could get a new release that has this fix?

**Comment by creswick** [comment]
I'm uploading 0.8.0.1 now.  Sorry about that!

**Comment by creswick** [comment]
...but you'll want 0.8.0.2, since an upstream dependency (cereal) change the way default instances are handled, which as it turns out, is a breaking change.

0.8.0.2 just bounds the cereal version, I'll have to actually fix it another time.
